### Create Client
POST http://localhost:4004/odata/v2/catalog-service02/Clients HTTP/1.1
Content-Type: application/json

{
    "name": "Kami",
    "lastName": "kaze",
    "eMail": "kami.kkz@gmail.com"
}

### Create Client
POST http://localhost:4004/odata/v4/catalog-service02/Clients HTTP/1.1
Content-Type: application/json

{
    "name": "John",
    "lastName": "Doe",
    "eMail": "john.doe@example.com",
    "address": {
        "street": "123 Main Street",
        "town": "Springfield",
        "zipCode": "12345",
        "country": "US"
    },
    "phone": [
        {
            "number": "5551234567",
            "phoneType": "Mobile",
            "notes": "Personal mobile phone"
        },
        {
            "number": "5559876543",
            "phoneType": "Home",
            "notes": "Home phone"
        }
    ]
}

